# Generated by Django 3.1.4 on 2020-12-16 09:06

from django.db import migrations, models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20201216_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[programs.validators.validate_file_extension]),
        ),
    ]
