# Generated by Django 3.1.4 on 2020-12-16 09:10

from django.db import migrations, models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20201216_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='upload',
            field=models.FileField(default=0, upload_to='documents/', validators=[programs.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
