# Generated by Django 3.1.4 on 2020-12-16 09:35

from django.db import migrations, models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20201216_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='upload',
            field=models.FileField(upload_to='documents/', validators=[programs.validators.file_size]),
        ),
    ]
