# Generated by Django 3.1.4 on 2020-12-17 02:52

from django.db import migrations, models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20201216_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='upload',
            field=models.FileField(upload_to='documents/', validators=[programs.validators.validate_file_extension, programs.validators.file_size]),
        ),
    ]
