# Generated by Django 2.2.5 on 2020-03-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_view_hide_completed',
            field=models.BooleanField(default=False, verbose_name='Hide Completed Tasks'),
        ),
    ]
