# Generated by Django 2.2.5 on 2020-03-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_view_hide_completed',
            field=models.BooleanField(default=False),
        ),
    ]
